name: Code scan

on:
  push:
    branches: [ main, develop, ncs ]
  pull_request:
    branches: [ main, develop, ncs ]

jobs:
  code-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check code with black
        run: |
          pip install black
          black -v --check --diff .
      - name: Check code with flake8
        run: |
          pip install flake8
          flake8 .
      - name: Check code with pydocstyle
        run: |
          pip install pydocstyle
          pydocstyle .